db.js
package.json
server.js

added mongo/mongoose, created method for finding/creating users, closes #7

---

app/routes/api.js
package.json
server.js

add express routing

---

app/routes/api.js

(feat) Added express routing for challenges and athletes

---

app/db/index.js
app/models/users.js
app/routes/api.js
app/strava.js

User model

---

app/models/users.js
app/routes/api.js
app/strava.js

redirects user to homepage after login

---

app/models/users.js
app/routes/api.js
app/strava.js

Setup users api

---

app/models/users.js

also fixed bug where user profile photo was not being saved correctly

refreshes all athlete data, not just token

---

app/routes/api.js

created POST route for creating challenges

---

app/routes/api.js
app/strava.js

(feat) get segments from strava API

---

app/routes/api.js
app/strava.js

(feat) get segment efforts from Strava API

---

app/models/users.js
app/routes/api.js
app/strava.js

Saves user's friends to db, setup API route for getting user's friends

---

app/strava.js

added challengeCount and record property to user's friends

---

Gruntfile.js
karma.conf.js
package.json

remove unneeded deps

---

app/models/segments.js
app/models/users.js
app/strava.js

(feat) add segements to database on lookup

---

app/models/challenges.js
app/routes/api.js
app/strava.js

retrieves segment effort for completed challenge, updates challenge

---

app/models/users.js

(feat) modify user schema to store fullName

---

app/routes/api.js
app/strava.js

(feat) get all stored segments

---

app/models/segments.js
app/models/users.js
app/strava.js

(feat) store user segments on login

---

app/strava.js

(bugfix) fix access token

---

app/models/challenges.js

adds due date when creating challenge

---

app/models/challenges.js
app/routes/api.js

(feat) add pending challenge route

---

app/models/users.js
app/strava.js

calls Strava API for user's friends only if user is new

---

app/models/challenges.js
app/routes/api.js
app/strava.js

adds functions to accept and reject a challenge

---

app/models/challenges.js
app/routes/api.js

saves more details re: user's segment effort to the challenge

---

app/models/challenges.js
app/strava.js

refactored pending challenges route

---

app/models/users.js
app/strava.js

fixes bug where user's friends were not being retrieved from strava

---

app/models/users.js

adds a statement to check if user has friends before saving

---

.gitignore
app/models/users.js

adds fullName property to user's friends

---

app/models/challenges.js

fixes bug where it was not checking for winner upon completion

---

app/models/challenges.js
app/models/segments.js
app/routes/api.js
app/strava.js

updates challenge with winner/loser, automatically checks for winner

---

app/models/users.js

adds default photo path

---

app/models/users.js
app/strava.js

Fixes duplicate segment bug

---

app/server.js
package.json

adds passport auth

---

app/models/users.js
app/strava.js

updates user's friends

---

app/models/challenges.js

returns challenges sorted by date

---

app/routes/auth.js
app/strava.js

retrieves and saves user's starred segments from strava

---

app/models/challenges.js
app/routes/auth.js

adds cron job to check challenge completion hourly

---

app/models/users.js
app/routes/auth.js
app/strava.js

sorts user segments and friends automatically

---

app/models/users.js

sets default photo for user's friends if no photo is provided
